# 🧪 SCRIPT DE TESTE PARA SUPABASE

# Execute este script no terminal para popular o banco de dados com dados de teste
# e verificar se o dashboard está funcionando corretamente

# 1. PRIMEIRO: Execute o SQL no Supabase
# - Vá para https://supabase.com
# - Acesse seu projeto: xqsocdvvvbgdgrezoqlf
# - Clique em "SQL Editor"
# - Cole o conteúdo do arquivo dashboard_test.sql
# - Execute (RUN)

echo "📊 SCRIPT DE TESTE DO DASHBOARD - PURPOSE FOOD"
echo "=============================================="
echo ""
echo "🎯 PASSOS PARA TESTAR O DASHBOARD:"
echo ""
echo "1️⃣ Acesse o Supabase:"
echo "   • URL: https://supabase.com"
echo "   • Projeto: xqsocdvvvbgdgrezoqlf"
echo "   • Vá para: SQL Editor"
echo ""
echo "2️⃣ Execute o script SQL:"
echo "   • Copie o conteúdo de: dashboard_test.sql"
echo "   • Cole no SQL Editor"
echo "   • Clique em: RUN"
echo ""
echo "3️⃣ Verifique os dados inseridos:"
echo "   • 8 produtos"
echo "   • 8 clientes"
echo "   • 10 pedidos"
echo "   • Dados financeiros"
echo ""
echo "4️⃣ Teste o dashboard:"
echo "   • Abra: http://localhost:5173"
echo "   • Faça login (se necessário)"
echo "   • Clique nos botões para testar"
echo ""
echo "🔧 COMO TESTAR OS BOTÕES NO CONSOLE:"
echo ""
echo "Abra o console do navegador (F12) e execute:"
echo ""
echo "// Adicionar event listeners de teste:"
echo "testDashboardButtons();"
echo ""
echo "// Verificar estado do sistema:"
echo "checkSystemStatus();"
echo ""
echo "✅ RESULTADOS ESPERADOS:"
echo "   • Botões respondem ao clique"
echo "   • Notificações aparecem no canto superior direito"
echo "   • Navegação entre páginas funciona"
echo "   • Dados reais do banco são exibidos"
echo ""
echo "❌ SE ALGO NÃO FUNCIONAR:"
echo "   • Verifique o console para erros"
echo "   • Confirme que o SQL foi executado"
echo "   • Verifique a conexão com Supabase"
echo "   • Verifique se está autenticado"
echo ""
echo "📋 ARQUIVOS DE TESTE DISPONÍVEIS:"
echo "   • dashboard_test.sql - Script SQL para popular dados"
echo "   • browser_test_dashboard.js - Script para testar botões"
echo "   • src/GUIA_TESTE_DASHBOARD.md - Guia completo de testes"
echo ""
echo "🚀 PRONTO PARA TESTAR!"
echo "Execute o script SQL no Supabase e depois teste o dashboard."